version: '3'
networks:
    app-tier:
      driver: bridge
services:
    app:
        build: .
        ports:
            - "5000:5000"
            - "9191:9191"
        networks:
            - app-tier 